export const routes = {
    home: '/',
    partner: '/partner',
    contact: '/contact',
    profile: '/profile',
    profilemycoin: '/profile/mycoin',
    profilebuyhistory: '/profile/buy-history',
    profilesellhistory: '/profile/sell-history',
    profileeditgateway: '/profile/edit-gateway',
    profilewithdraw: '/profile/withdraw',
    profilewithdrawcreate: '/profile/withdraw/create',
    profiledeposit: '/profile/deposit',
    profiledepositcreate: '/profile/deposit/create',
    coin: '/coin',
    about: '/about',
    terms: '/terms',
    privacy: '/privacy',
    disclaimer: '/disclaimer',
    methodology: '/methodology',
    login: '/login',
    forgotpassword: '/forgot-pass',
    signup: '/signup',
    pagenotfound: '*',
    detailcoin: '/coin/:slug',
};
