export { default as DefaultLayout } from './DefaulLayout/DefaultLayout';
export { default as Home } from './Home/Home';
export { default as DepositWithdraw } from './DepositWithdraw/DepositWithdraw';
export { default as Blog } from './Blog/Blog';
export { default as Aboutus } from './Aboutus/Aboutus';
export { default as Contactus } from './Contactus/Contactus';
export { default as Image } from './Image/Image';
export { default as Button } from './Button/Button';
export { default as PageNotFound } from './PageNotFound/PageNotFound';
